version: '3.4'
services:
  webex-bot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    network_mode: "bridge"
    restart: on-failure
    volumes:
      - ./:/bot/
    ports:
      - "7001:7001"
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    command: node --use_strict index.js
